### ISSUE TITLE
Enable Loading 2 Different Instances of Launch Darkly

### ISSUE THREAD

**Issue by gregra81** [launchdarkly/js-client#101]
Hi,
We have a requirement to integrate Feature Flags from two different LD projects. SDK currently supports a singleton of the SDK instance with a specified project.

Anything I can do about it?

**Comment by eli-darkly** [comment]
The LaunchDarkly JavaScript SDK doesn't enforce singleton usage; each time you call `ldclient.initialize()`, you will get a new and independent client instance. Or have I misunderstood the question?

**Comment by gregra81** [comment]
Oh, I was under the impression that you could create only one instance of the SDK. Thank you for that!
