### ISSUE TITLE
Proposal: replace export default with named exports

### ISSUE THREAD

**Issue by 1999** [launchdarkly/js-client#103]
Right now the main file has `export default { initialize, version };` export which looks a bit weird to me:

1) if the main object exported is an object where we know all keys, why not export it with two separate named exports? This will also improve the intellisense support in the editors
2) unfortunately for legacy builders default exports are a pain in the ass: it's often just hard to import stuff. For instance, we have a typescript+webpack+karma for one of our packages, and while it's easy to fix the file imports for TS compiler, it becomes tricky to debug issues in the browser:

![image](https://user-images.githubusercontent.com/73191/42613088-53dc66ee-85e2-11e8-99a1-6dfc5881be92.png)

**Comment by apucacao** [comment]
Thanks for bringing this up @1999. 

We’ve actually been working on doing away with default exports, and we should have a release ready soon. We’ll keep you posted.

**Comment by apucacao** [comment]
Hi @1999 ,

I forgot to let you know that we released this as part of [2.4.0](https://github.com/launchdarkly/js-client/releases/tag/2.4.0).
