### ISSUE TITLE
IE11 - 'Promise' is undefined

### ISSUE THREAD

**Issue by theonesuperdave** [launchdarkly/js-client#106]
I have the LD client running perfectly in my SPA, except that Internet Explorer 11 doesn't like the ES6 Promise usage which is unsupported. `Promise` is still being used in the `ldclient.min.js` file; everything works fine in Chrome and Edge browsers.

> [object Error]{description: "'Promise' i...", innerError: undefined, message: "'Promise' i...", name: "ReferenceEr...", number: -2146823279, stack: "ReferenceEr..."}

Looks like it's complaining about `EventSender.js (54,9)` but I found `Promise` used in other modules as well.

After looking at the docs, I wasn't able to find any guidance for this one, so please advise when you can.

**Comment by apucacao** [comment]
Hi @theonesuperdave,

We currently recommend using a polyfill like [`es6-promise`](https://github.com/stefanpenner/es6-promise) to support `Promise` in older browsers.

Apologies for the lack of guidance there — we're going to update the README and docs now.

**Comment by theonesuperdave** [comment]
OK. Thanks, @apucacao. I'm already looking at that polyfill now. I noticed other non-compliant IE11 items (`const`, for example) were removed from the minified file, and thought maybe I had missed something in the docs..
