### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by elazar** [launchdarkly/js-client#108]
We've had over 3,900 recurrences of this issue in the last week. It appears to happen in Chrome 67 and 68 on Windows.

```
SyntaxError: Unexpected end of JSON input
1 File "webpack:///./node_modules/ldclient-js/dist/ldclient.es.js" line 1 col 14836 in EventSource.put
function createCommonjsModule(e,t){return e(t={exports:{}},t.exports),t.exports}var base64=create...
2 File "webpack:///./node_modules/logrocket/dist/build.umd.js" line 1679 col 1 in EventSource.o
return func.apply(this, args);
```

**Comment by eli-darkly** [comment]
Hmm. What version of the JS SDK are you using?

**Comment by elazar** [comment]
@eli-darkly 2.1.0. Suppose we could try upgrading. Any idea if this was a known issue in that version or versions since?

**Comment by eli-darkly** [comment]
It's not something we've seen before as far as I know, but knowing the version helps in tracking down the exact code path that's responsible.

**Comment by eli-darkly** [comment]
Also, could you email your account name to eli@launchdarkly.com so we can try to reproduce this problem with your particular flag data?
