### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by vireshshah** [launchdarkly/js-client#111]
I'm getting below minor warning in console. It would be great, if we can fix it.

> [LaunchDarkly] "default export" is deprecated, please use "named LDClient export"

**Comment by atrakh** [comment]
Hi @vireshshah,

The warning you're seeing is an indication that the default export for the JavaScript SDK will be removed in a future version. To resolve this issue, we'd recommend using syntax for a named import when importing the SDK. For example, the following are valid imports:
```
import * as LDClient from 'ldclient-js'
ldclient = LDClient.initialize('YOUR_CLIENT_SIDE_ID', {key:"key"})
```
or
```
import { initialize } from 'ldclient-js'
ldclient = initialize('YOUR_CLIENT_SIDE_ID', {key:"key"})
```

**Comment by vireshshah** [comment]
Thanks @atrakh
