### ISSUE TITLE
LaunchDarkly's js-client is closing browser tabs

### ISSUE THREAD

**Issue by Sawtaytoes** [launchdarkly/js-client#119]
All of a sudden, we started receiving reports of clients having our app close the browser on iPads and in Chrome after logging in. We didn't add any code to intentionally close the browser, nor should it be possible.

Calling `window.close()`, you see this message:
> Scripts may close only the windows that were opened by it.

Today, I saw that same message coming from `ldclient.es.js` for this line of code:
```js
o.disconnect=function(){clearTimeout(l),l=null,close()}
```
`close()` here refers to `window.close()`.

I wonder if the browser can get into a strange state where `window.close()` would actually close the tab you're in.

I found the same line here:
https://github.com/launchdarkly/js-client/blob/8e9b46037f253c25bdbbb3ba73aad36ee966c636/src/Stream.js#L23

Did you mean to call `es.close()` or `stream.close()` instead?

Also, when would a fix be put out? I'd like to get this updated asap for our users.

**Comment by apucacao** [comment]
@Sawtaytoes — we just released 2.7.2 with a fix for this bug.

**Comment by Sawtaytoes** [comment]
Thanks! I'll pull it in. Appreciate the quick response and fix.
