### ISSUE TITLE
LDEventName type does not allow for "change:<flag-name>"

### ISSUE THREAD

**Issue by rmanalan** [launchdarkly/js-client#122]
https://github.com/launchdarkly/js-client/blob/556711701d74d7c4a50981cae0547ec78f3d5eec/typings.d.ts#L24

Because the `LDEventName` ts type is defined as `'ready' | 'change'`, you can't use this syntax for `ldclient.on()`:

```
ldclient.on('change:<flag-name', cb);
```

**Comment by eli-darkly** [comment]
OK, version 2.7.3 is out now with a fix for this. Sorry about the error.
