### ISSUE TITLE
Base64 dependency breaks fuse-box bundler

### ISSUE THREAD

**Issue by repl-sean-heintz** [launchdarkly/js-client#124]
**Issue:**
We're trying to use the LaunchDarkly client-side SDK in a project which creates a bundle using fuse-box (https://fuse-box.org/). Unfortunately, the SDK does not work with this bundler as it includes the `Base64` package which does not comply with the package.json spec for package names (https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields). The spec requires that packages be published under a name that is **all lowercase**. FuseBox fails to import any packages that don't meet this requirement.

**Proposed fix:**
Switch to a different base64 library which is published with a valid name.

I'd be happy to open a pull request which fixes this issue.

**Comment by eli-darkly** [comment]
Thanks for alerting us to this. We'll have a fix out shortly.

**Comment by eli-darkly** [comment]
OK, that turned out to be easy to fix, so the new version to use is 2.7.5.
