### ISSUE TITLE
Proposal: Export the React Context object in addition to destructuring its Consumer and Provider

### ISSUE THREAD

**Issue by spiceboi** [launchdarkly/js-client#143]
About to implement `ldclient-react` in a React project that is pretty hooks-heavy, and would really like to be able to `useContext` with this package. For example:

```js
import { LDContext, withLDProvider } from 'ldclient-react'
import { useContext } from 'react'

function MyComponent() {
  const { flags, ldClient } = useContext(LDContext)
  return flags.foo ? <div /> : <></>
}

export default withLDProvider({ clientSideID: 'your-client-side-id' })
```

It should be minor, and I can put up a PR today if it's welcome. Thanks!

**Comment by torchhound** [comment]
Hi @spiceboi that sounds like a potentially reasonable change. We always welcome open source contributions and would gladly review a PR on this subject.

**Comment by EstebanMarin** [comment]
Keen on seening the implementation!

**Comment by spiceboi** [comment]
See https://github.com/launchdarkly/js-client/pull/144
