### ISSUE TITLE
Uncaught TypeError: Cannot read property 'flagname' of undefined

### ISSUE THREAD

**Issue by IceCreamYou** [launchdarkly/js-client#27]
The error has this stack trace:

```
TypeError: Cannot read property 'flagname' of undefined
at Object.u [as modifications] (/vendor/ldclient-js/ldclient.min.js:1:4074)
at f (/vendor/ldclient-js/ldclient.min.js:1:1443)
at /vendor/ldclient-js/ldclient.min.js:1:1412
at /vendor/ldclient-js/ldclient.min.js:11:22303
at XMLHttpRequest.<anonymous> (/vendor/ldclient-js/ldclient.min.js:11:22056)
```

I tracked it down, it looks like this happens because `modifications` gets called with an undefined `newObj`, which happens when `updateSettings()` gets called with an undefined `settings` parameter, which happens when `requestor.fetchFlagSettings` tries to get settings but the response code is not `200` or the response does not have a `Content-type` of `application/json` due to how `fetchJSON` handles those cases. Unfortunately I do not know what the faulty response was in this case as the error was recorded using an error-tracking service.

**Comment by apucacao** [comment]
Thanks for the report @IceCreamYou . I'll take care of this now.

**Comment by apucacao** [comment]
Hi @IceCreamYou , this should be fixed now. Thanks again for reporting. Have a good weekend!
