### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by IceCreamYou** [launchdarkly/js-client#29]
This happens on index.js line 91 - apparently somehow `flags` is undefined when `variation` is called in the callback for the `ready` event. Our error tracker reports that this has happened in just a small fraction of page loads, so it's working most of the time. We're using the `ldclient-js` npm module v1.1.3.

I think this is another symptom of the same problem as #27: when a request to the LaunchDarkly service returns an error, the LD script gets no flags back, and that causes problems. (This might not even be an issue with LD - it could be that the internet flickered while the request was being made.)

**Comment by apucacao** [comment]
Thanks @IceCreamYou – we'll get a fix out shortly.

**Comment by apucacao** [comment]
We just published `1.1.4` with extra checks to avoid this error. Thanks again @IceCreamYou .

**Comment by jacksweat** [comment]
helper.js:311 Uncaught (in promise) TypeError: Cannot read property 'hasOwnProperty' of undefined
help me
vue js + laravel 5.6

**Comment by apucacao** [comment]
Hi @jacksweat, apologies for the inconvenience. What version of the SDK are you using?
