### ISSUE TITLE
Remove sizzle?

### ISSUE THREAD

**Issue by tleunen** [launchdarkly/js-client#34]
Hi,

The lib is currently using Sizzle, which is not a small library just to do one simple thing, getting the nodes for a specific selector ([see this line](https://github.com/launchdarkly/js-client/blob/master/src/GoalTracker.js#L39))
```js
var elements = Sizzle(selector);
```

Would it be possible to remove this dependency and use `document.querySelectorAll` instead?
`QuerySelectorAll`is widely supported now so it seems Sizzle is definitely not required.

**Comment by jakepusateri** [comment]
Changing this line to 
```javascript
var elements = document.querySelectorAll(selector);
```
and removing the `require('sizzle')` reduces the bundle size from 10.76 kB to 3.65 kB.

**Comment by apucacao** [comment]
Thanks guys. It looks like we indeed don't need Sizzle anymore.

**Comment by tleunen** [comment]
Thanks @apucacao. Closing the ticket since the change is merged and a new version has already been released.
