### ISSUE TITLE
Add support for Bower

### ISSUE THREAD

**Issue by vitherain** [launchdarkly/js-client#40]
Please add support for Bower as dependency manager.
We need it for our project where is not sutiable to use NPM.

Thanks!

**Comment by apucacao** [comment]
Hi @vitherain , 

Thanks for reaching out. And sure we can do that :)

**Comment by apucacao** [comment]
Hi @kazazor ,

We haven't forgotten about this. We're planning on adding Bower support soon.

Cheers,
Alexis

**Comment by kazazor** [comment]
I think you had me confused with @vitherain :)

**Comment by apucacao** [comment]
Oops sorry about that! 😅

**Comment by atrakh** [comment]
Hi @vitherain- 

I know it's been a little while, but I'm following up to let you know that the JS SDK should be installable via bower with the following command:
```
bower install https://app.launchdarkly.com/snippet/ldclient.min.js
```

Please try that and let me know how it goes.
