### ISSUE TITLE
EasyList's EasyPrivacy blocking LaunchDarkly urls

### ISSUE THREAD

**Issue by dcousineau** [launchdarkly/js-client#41]
See easylist/easylist#391 for more information.

I'm not sure what the proper solution is other than writing up a warning for users. Your code shows the ability to change baseurls so proxies can be written by end-users as a workaround as need-be.

I've also sent emails, just documenting this as far and wide as possible :)

**Comment by adamlaunchingdarkly** [comment]
@dcousineau - thank you for the support!  We have reached out as well.  Hoping for a speedy resolution.

**Comment by adamlaunchingdarkly** [comment]
@dcousineau - thanks again for reporting this.  

We've worked with EasyList to restrict the listing to events.launchdarkly.com (https://github.com/easylist/easylist/search?utf8=%E2%9C%93&q=launchdarkly&type=).  This change ensures that our core feature flagging service will not be blocked by Easylist or other third parties that use its listing.
