### ISSUE TITLE
Add support for promises instead events

### ISSUE THREAD

**Issue by kazazor** [launchdarkly/js-client#43]
In today's js world, I would expect the SDK to have support for promises instead of `ready` events an so on.. Or at least in addition to..

**Comment by apucacao** [comment]
Hi @kazazor ,

Thanks for the feedback. A promise interface would indeed be convenient for the `ready` event. We'll add support for that shortly.

**Comment by apucacao** [comment]
Hi @kazazor ,

We haven't forgotten about this. We're planning on adding support for promises soon.

Cheers,
Alexis

**Comment by atrakh** [comment]
Hi @kazazor -

Following up to let you know that versions 1.3.X of the JavaScript SDK, it is now possible to wait for SDK readiness using `ldClient.waitUntilReady()` which returns a Promise.

Thanks,
Arnold
