### ISSUE TITLE
Refactor build system to use rollup

### ISSUE THREAD

**Issue by tdeekens** [launchdarkly/js-client#52]
The current build system seems to be around webpack. However, generally rollup works a bit better for libraries whereas webpack works super nice with applications.

Would there be interest in moving the build system to rollup? Another option then would also be to refactor all code to ES6 code while building UMD, ESM and CJS bundles.

I've done such thing quite a few times now and could offer my help just wanted to clarify first if that brings up interest.

**Comment by tdeekens** [comment]
Due to lack of interest from the repositories owners I will close this.

**Comment by apucacao** [comment]
Hi @tdeekens —

Sorry about that! We missed this one.

We do favor anything that makes it easier for developers to use our SDK. So I'm curious to hear more about this.

I'm not very familiar with Rollup. At a glance, it seems like the SDK would also be (written and) usable as an ES6 module, in addition to UMD, ESM and CJS modules. Would updating to Webpack 2 achieve the same thing?

**Comment by tdeekens** [comment]
You can achieve the same thing using webpack@2. However, it's generally kind of true that webpack is for apps and rollup for libraries. It's just a bit simpler to configure and doesn't come with loads of features libraries won't need (e.g. code splitting).

**Comment by tdeekens** [comment]
So how would you like to go about this? What would be a preferred way? Should I open a PR removing webpack for rollup trying to show some benefits in using it?

**Comment by apucacao** [comment]
That would be great, thanks!
