### ISSUE TITLE
Request: better error messages for initialize

### ISSUE THREAD

**Issue by mickeyreiss-visor** [launchdarkly/js-client#54]
I tried calling `LDClient.initialize('my key')`, and I forgot to pass a user parameter. The error message I received was confusing. It would be great if the error more clearly explained the issue or linked to online docs.

![image](https://user-images.githubusercontent.com/30812527/33411542-180d2b24-d53b-11e7-912c-c41ac9bdc4d0.png)
![image](https://user-images.githubusercontent.com/30812527/33411550-23c3f90c-d53b-11e7-87ca-6e9ae11d4554.png)

**Comment by apucacao** [comment]
Thanks for reporting that @mickeyreiss-visor . We'll have a fix for that out shortly.
