### ISSUE TITLE
localstorage unavailability during initialization

### ISSUE THREAD

**Issue by mickeyreiss-visor** [launchdarkly/js-client#55]
Is it the caller's responsibility or the SDK's responsibility to handle localStorage errors during initialization? 

https://github.com/launchdarkly/js-client/blob/39495f9851b83ed743f5b590639f683079e60ba0/src/index.js#L256-L263

I'm wondering if the call to `setItem` in the catch block could possibility throw an uncaught exception.

My concern comes from the fact that we often see `localStorage` throw `SecurityException`s in production, especially on mobile, where it is locked when the device is locked or maybe when the user is in incognito/private browsing mode.

**Comment by apucacao** [comment]
Hi @mickeyreiss-visor ,

Thanks for reporting this one. The SDK should be a good citizen and handle those. We'll get a fix out soon.

Alexis

**Comment by mickeyreiss-visor** [comment]
Thanks!

**Comment by apucacao** [comment]
Hi @mickeyreiss-visor,

Your contribution just went out as part of version `1.2.0`. Thanks again!

Cheers,
Alexis
