### ISSUE TITLE
Targeting by uses's IP

### ISSUE THREAD

**Issue by MartinNuc** [launchdarkly/js-client#61]
We are trying to target users by IP address. This works for backend LD client but doesn't work for js-client.

When I send IP in `ip` field among `key` according to https://docs.launchdarkly.com/v2.0/docs/js-sdk-reference it works but it requires browser to fetch user's public IP somewhere.

IMHO user's public IP should be obtained by LD server when browser is asking for status of feature flags.

What is a correct way how to target js-client users by their IP address?

**Comment by zmdavis** [comment]
Sorry to hear you're having trouble.

The information in the documentation regarding the geolocation service is outdated and no longer applies, though it was merely saying that country would be automatically inferred from the supplied IP.

Targeting by IP should work the same in the js client as any of the other clients -- you must provide the IP as an attribute to the user object, eg

```
var user = {
  "key": "aa0ceb",
  "firstName": "Ernestina",
  "lastName": "Evans",
  "email": "ernestina@example.com",
  "ip": "12.34.567.89"
};
```

The js client does not attempt to gather the IP automatically, you must explicitly provide it.

Let me know if that clears things up, or if you're having other problems.

**Comment by MartinNuc** [comment]
That's what I was afraid of :-/ That means we need 3rd party service to get user's public IP address to target browser users by IP.

I thought LD would add `ip` field automatically on LD servers when receiving http request. So browser client doesn't have to deal with IP at all.

We will use https://www.ipify.org to get that address then. Thank you.

**Comment by zmdavis** [comment]
Because LaunchDarkly does flag evaluations in the SDK and not on our servers, it's not possible for us to automatically add the IP prior to evaluation.  That's why it's required to specify it manually in the client.  

Hopefully ipify works out for you -- let us know if you run into any other problems.

**Comment by MartinNuc** [comment]
Oh I didn't know that evaluation is done in browser. When I load my app I can see http request to LD server like this: `GET https://app.launchdarkly.com/sdk/eval/58d39fa40178100929327bb8/users/eyJrZXkiOiJBLTM1IiwiYW5vbnltb3VzIjp0cnVlfQ`

In the response there is an object with all feature flags and their status (on/off). This case is evaluated on server?

**Comment by zmdavis** [comment]
Sorry, you're right -- I misspoke.  Our JavaScript client works slightly differently to the rest of our clients, so the evaluation happens on our servers not in browser.

I discussed this with our CTO -- while it's technically possible for us automatically fetch the IP at evaluation time when using the js client, there are a number of potential downsides to that approach and it's not something we're planning to provide any time soon.

**Comment by MartinNuc** [comment]
Thank you for answer.

Please consider it wisely. This is quite inconvenient. It forces apps to depend on 3rd party services instead of providing this feature by LD itself.

**Comment by zerostatic-review** [comment]
Is it still true that if you supply LD with the IP address, it will automatically populate the users Country or does Country have to be provided?
