### ISSUE TITLE
Privacy Badger blocks LaunchDarkly urls

### ISSUE THREAD

**Issue by Kerumen** [launchdarkly/js-client#62]
Similar to https://github.com/launchdarkly/js-client/issues/41, the extension [Privacy Badger](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp?hl=fr) blocks all LaunchDarkly urls making our flags useless.

https://github.com/EFForg/privacybadger/issues/1813

**Comment by jkodumal** [comment]
@Kerumen Thanks for the report-- we'll work with Privacy Badger to restrict blocking to `events.launchdarkly.com`, as we did in #41. Looking at this a bit deeper, I think we'll also modify the JS SDK to respect the Do Not Track header. 

We're getting started on both fronts immediately.

**Comment by ghostwords** [comment]
I haven't had a chance to look at what exactly causes Privacy Badger to decide to start blocking `launchdarkly.com` resources, but generally speaking, Privacy Badger doesn't work from a blacklist but instead watches for what it considers to be tracking in each user's browser. Privacy Badger then starts blocking domains after having seen them perform tracking across three separate sites.

Would you be able to adopt the [EFF Do Not Track policy](https://www.eff.org/dnt-policy)? If your company can and will abide by the policy's requirements, posting the policy on your domains will tell Privacy Badger to allow loading of resources from those domains.

**Comment by jkodumal** [comment]
@ghostwords I believe so, that's what we're attempting to do now by modifying our JS SDK and hosting a `dnt-policy.txt`.

**Comment by ghostwords** [comment]
Could you share any example pages (one is good, three distinct domains would be great) where I could see your service in action?
