### ISSUE TITLE
IE10 breakage due to 'const' usage

### ISSUE THREAD

**Issue by turnerniles** [launchdarkly/js-client#69]
Similar to #7, IE10 does not support the variable const. 

The client script contains `const` coming from line of code [here](https://github.com/launchdarkly/js-client/blob/2a2506389613575cf667cf001316a4bc875ee514/src/EventEmitter.js#L5):

See it's appearance here: https://cdn.jsdelivr.net/npm/ldclient-js@1.5.0/dist/ldclient.js

Would you consider changing this to `var`? PR #68

**Comment by turnerniles** [comment]
@apucacao thanks for the quick turn around! Do you know when the package will next be released on npm?

**Comment by apucacao** [comment]
We'll get a release out shortly.

**Comment by turnerniles** [comment]
@apucacao awesome! thank you!!
