### ISSUE TITLE
Issue importing LDClient into Angular 5 application

### ISSUE THREAD

**Issue by germs12** [launchdarkly/js-client#83]
I am attempting to import `LDClient` into an Angular [service](https://angular.io/guide/architecture-services) and I'm getting an interesting error.  I am following this [post](https://blog.launchdarkly.com/integrating-feature-flags-in-angular-v4/) from the LaunchDarkly blog.

```ts
import * as LDClient from 'ldclient-js'
```

When I use `LDClient` as the documentation suggests: 

```ts
this.ldClient = LDClient.initialize('abc123def456', {...})
```

I get the following error in the console:

```js
AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: LDClient.initialize is not a function
    at new LaunchDarklyService (launchdarkly.service.ts:16)
    at _createClass (core.js:10931)
    at _createProviderInstance$1 (core.js:10907)
    at resolveNgModuleDep (core.js:10892)
    at NgModuleRef_.get (core.js:12129)
    at resolveDep (core.js:12619)
    at createClass (core.js:12489)
    at createDirectiveInstance (core.js:12326)
    at createViewNodes (core.js:13784)
    at createRootView (core.js:13673)
```

I logged the `LDClient` into the console and saw a method `default` and was able to get this working by calling `LDClient.default.initialize(...)`

```ts
this.ldClient = LDClient.default.initialize('abc123def456', {...})
```

Version:
`"ldclient-js": "^1.7.0"`

Any idea what I'm doing wrong?  Thanks!

**Comment by apucacao** [comment]
It looks like there's something going on with the default export in TypeScript specifically.

We emit ES modules (along with CommonJS and UMD modules). `./dist/ldclient.es.js` does have a default export, meaning that the import in TS should just be `import LDClient from 'ldclient-js'`.

However, we used to do this: `module.exports = { initialize, version };`. From what I understand, that equates to the `export default { initialize, version };`, but evidently, TS doesn't think so.

I found that TS has this option available for making this work properly, in your `tsconfig.json`:

```
"allowSyntheticDefaultImports": true,
```

Does that allow you to avoid `LDClient.default.initialize`? I tried in one of our TS projects and it helped, but let me know if it works for you. 🙂

**Comment by germs12** [comment]
@apucacao Thank you again for the prompt and detailed response.  I have tried out your suggestions and I have the following notes to report back.

1) It works. 🍰 
2) If I change my import from `import * as LDClient from 'ldclient-js'` to `import LDClient from 'ldclient-js'`, it compiles correctly but I get a TypeScript error in my editor (VSCode) saying `Module ''ldclient-js'' has no default export`.
3) If I only update my `tsconfig.json` and leave my import as `import * as LDClient from 'ldclient-js'` I still need to call `default` to make it work.

🌵
