### ISSUE TITLE
Content-type Equality Check Problem

### ISSUE THREAD

**Issue by OmriAharon** [launchdarkly/js-client#87]
Would like to report a possible bug on [this line.](https://github.com/launchdarkly/js-client/blob/master/src/Requestor.js#L11)

We're using [Cypress](https://github.com/cypress-io/cypress) in our project, and as part of it we're mocking network requests by saving setup XHR responses as fixture files. One of those XHR requests is the LaunchDarkly GET request to get our feature flags.

However, since we now read a file to serve as a mock for the request, the `content-type` header as part of the response is added with `charset=utf-8` which results in this value being: `application/json; charset=utf-8`, thus failing the said line above.

Do you see any problem in modifying the condition to:
```js
const contentType = xhr.getResponseHeader('Content-type');
if (xhr.status === 200 && contentType && contentType.indexOf(json) > -1) {
    ...
}
```

**Comment by eli-darkly** [comment]
Thanks for pointing that out - indeed, we shouldn't be relying on an exact match like that. We're working on getting a big JS release out soon and this could go into that - although if this is blocking your work right now, I can try to put out a smaller patch release sooner.

**Comment by OmriAharon** [comment]
If you could do that it would be greatly appreciated!

**Comment by eli-darkly** [comment]
Should be fixed now in the latest release.
